---
name: Config-Any
version: 0.04
author:
  - 'Joel Bernstein <rataxis@cpan.org>'
abstract: 'Load configuration from different file formats, transparently'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Module::Pluggable: 3.01
  Test::More: 0
  version: 0
provides:
  Config::Any:
    file: lib/Config/Any.pm
    version: 0.04
  Config::Any::General:
    file: lib/Config/Any/General.pm
  Config::Any::INI:
    file: lib/Config/Any/INI.pm
  Config::Any::JSON:
    file: lib/Config/Any/JSON.pm
  Config::Any::Perl:
    file: lib/Config/Any/Perl.pm
  Config::Any::XML:
    file: lib/Config/Any/XML.pm
  Config::Any::YAML:
    file: lib/Config/Any/YAML.pm
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
